language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE espeak_test;' -U postgres
script:
- npm run jest-test
env:
  global:
    - secure: "G7XWWAfLJK81ukU4Fk0uG24JX/ZajJ5Z+MOW1CLELYHRdNd0nOBMrd0HezuPlfgDDEHLHTwJ3+BflWOE37EUJxoWWPKvjFzRoR+1MtFp+9Be3ypne4T5QI3vANtv9N5rPUpAlAqXlZGboMJDoZ0xVcJIlSilUpDEtPfaPmzaRkbSj+697f2r8sgSO8Ih03vlp4sC1/rjQ7K9QyjOAC3sc1IxXbIuEKVVKwcQvKR1nBngr5E1n+Ng6J1wsDj/QKEQiUB/8Gvi8vhPMihbdoIy1XU9K3V3fa3wnP5YvxIf17a11cjIIa34NizPJ1z/xuzBf1UVPqrWAfRcuzQzYXbxBrLbEFoyH+QsngMQZzrJi9uuf/bT8VO4F9NWtg3c6F/hVpQZmLqV0zz2qBpfqOmSDUW8FlXkI9JWs174zAzgWTvL8tTUzcuY/3qH4/BebyZGfIr3RDJJbwJbe1HXnSPXA3uy1ld/aGNi2sIu/RUH9vBLBG6UASdeKyogwQops3YhtvgQPshjrhDJ2Xe5NVMrpBkPPUCCDQoPLDqPcMWgYdKcnOrh7mZhLOPd6Yjj6i4CfYO3WtOo+Mca5T6kiHTXlTQUtRonw17z6KVP7IsbA+2zz7z4/G/09SOqIjlpS/60rvPqjpgCJWFWbedY3h/5IpFwdpOLwRQtWCf0CbNmQBk="
notification:
- email: false
deploy:
  provider: heroku
  api_key:
    secure: Zc6foUTiWXjyaNyARxsm5zfLptgZYU6j+NWXUZzl0x6tB1NVy39KOwd41tfCXjFM4WOBvVFpLaloQXSrD4WHMKWNcew1HDryK2Nq+4Dr/OhOD6JoGHhSEpfAPpyEFCe2SX3eO0cLq6r8GRIOEa6c205uDq5Eht2Uy0zRdMTG7+4ZhEBIg/DDNvKHxG4O6nl+kRXCMQXJwsIKDe8HTpF3vCWQFrOrCs6+oZNwygN1xd7sU2xbPlOPtlxD4Cmh8NeCVik4So5JMnov65LY8Fwm7zdU0YpbPn7+yknl9tWAw//IulYKbkcavfg1uyodnhoKjfwj+mZ/8JLdfE4cWNZ3qYhjQouQDQxglMrFZjqRYl6CNPuvprGo+bToXuZnor7/42b2Xm7xZiCc09nZ9IafLHCabmUlBFGfIezzglJeyR3CQczdNWd+iAVk4mqbKGGhvSVImkB7BmGINeGy+S9UpnwxPS1lALxxXiBUR2rnRHd9wqeeE1+ie7kPHHwEkZ+8Gju84jstLVjENC6LK45USGigC2SuPtp0vAEk9KFWD+VIZc70n9CEPHiZTILMR0lCF5mVnnnlyPfNUvJQVwlxa+tGvC64Nt+ZXVB58bHw6c8tF6VqRUgrFMCkdQtncIEauHTYuHehvpOKTqCI6UxEsMvlUAxhL7RL9FxELYzJQM4=
  app: espeak-be-opa
  skip_cleanup: true
